<?php
session_start();
if (!isset($_SESSION["login"])) {
    header("Location: login.php");
    exit;
}

require_once 'vendor/autoload.php'; // Composer autoload

use TCPDF;

include "koneksi.php";

$rekap_type = $_GET['rekap_type'] ?? '';

if ($rekap_type == 'mahasiswa') {
    $query_rekap = "
    SELECT 
        a.waktu_absen, 
        a.nim, 
        m.nama AS nama_mahasiswa, 
        mk.nama_mk, 
        d.nama AS nama_dosen 
    FROM 
        absensi a
    LEFT JOIN 
        mahasiswa m ON a.nim = m.nim
    LEFT JOIN 
        mata_kuliah mk ON a.id_mk = mk.id_mk
    LEFT JOIN 
        dosen d ON mk.id_dosen = d.id
    WHERE
        a.nim IN (SELECT nim FROM mahasiswa)";
} elseif ($rekap_type == 'tendik') {
    $query_rekap = "
    SELECT 
        a.waktu_absen, 
        t.nipy AS nipy_tendik, 
        t.nama AS nama_tendik, 
        t.jabatan 
    FROM 
        absensi a
    LEFT JOIN 
        tenaga_kependidikan t ON a.nim = t.nipy
    WHERE
        a.nim IN (SELECT nipy FROM tenaga_kependidikan)";
} else {
    die('Jenis rekap tidak valid.');
}

$result_rekap = mysqli_query($koneksi, $query_rekap);
if (!$result_rekap) {
    die('Query Error: ' . mysqli_error($koneksi));
}

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Admin');
$pdf->SetTitle('Rekap Absensi');
$pdf->SetSubject('Rekap Absensi');
$pdf->SetKeywords('TCPDF, PDF, rekap, absensi');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Rekap Absensi ' . ucfirst($rekap_type), 'Generated by Admin');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('dejavusans', '', 12);

// Generate HTML content
$html = '<h2>Rekap Absensi ' . ucfirst($rekap_type) . '</h2>';
$html .= '<table border="1" cellpadding="5">';
$html .= '<thead><tr>';
$html .= '<th>Waktu Absen</th>';
if ($rekap_type == 'mahasiswa') {
    $html .= '<th>NIM</th>';
    $html .= '<th>Nama Mahasiswa</th>';
    $html .= '<th>Mata Kuliah</th>';
    $html .= '<th>Nama Dosen</th>';
} elseif ($rekap_type == 'tendik') {
    $html .= '<th>NIPY</th>';
    $html .= '<th>Nama Tendik</th>';
    $html .= '<th>Jabatan</th>';
}
$html .= '</tr></thead><tbody>';

while ($row = mysqli_fetch_assoc($result_rekap)) {
    $html .= '<tr>';
    $html .= '<td>' . htmlspecialchars($row['waktu_absen'], ENT_QUOTES, 'UTF-8') . '</td>';
    if ($rekap_type == 'mahasiswa') {
        $html .= '<td>' . htmlspecialchars($row['nim'], ENT_QUOTES, 'UTF-8') . '</td>';
        $html .= '<td>' . htmlspecialchars($row['nama_mahasiswa'], ENT_QUOTES, 'UTF-8') . '</td>';
        $html .= '<td>' . htmlspecialchars($row['nama_mk'], ENT_QUOTES, 'UTF-8') . '</td>';
        $html .= '<td>' . htmlspecialchars($row['nama_dosen'], ENT_QUOTES, 'UTF-8') . '</td>';
    } elseif ($rekap_type == 'tendik') {
        $html .= '<td>' . htmlspecialchars($row['nipy_tendik'], ENT_QUOTES, 'UTF-8') . '</td>';
        $html .= '<td>' . htmlspecialchars($row['nama_tendik'], ENT_QUOTES, 'UTF-8') . '</td>';
        $html .= '<td>' . htmlspecialchars($row['jabatan'], ENT_QUOTES, 'UTF-8') . '</td>';
    }
    $html .= '</tr>';
}
$html .= '</tbody></table>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('rekap_absensi_' . $rekap_type . '.pdf', 'D');
?>
